### ISSUE TITLE
Wrong naming of voidDoubleIntString class

### ISSUE THREAD

**Issue by mle-enso** [evainga/JavaBasics#2]
To be compliant with Java naming conventions as shown [here](http://www.oracle.com/technetwork/java/codeconventions-135099.html) you should name the class voidDoubleIntString better VoidDoubleIntString!

**Comment by evainga** [comment]
ok, thanks, changed that

**Comment by mle-enso** [comment]
Well, you just changed the class name to an uppercase beginning, but left the filename unchanged, that's as already mentioned inconsistent and therefore wrong.

**Comment by mle-enso** [comment]
By the way, insert anywhere in your commit comment the string "#2" to reference this issue, so its easier to link commits directly to issues displayed here.

**Comment by evainga** [comment]
something weird happening here. i switched both an in my eclipse and windows explorer it looks as if the file is beginning with uppercase. when i just pushed in my console, i saw that the file there appiears in lower case. seems like git didnt get that change?!

**Comment by evainga** [comment]
got it now. had to rename to something else, push it and then switch back to the old name. Now I think Git also got the change
