### ISSUE TITLE
Not able to run my java files

### ISSUE THREAD

**Issue by evainga** [evainga/JavaBasics#4]
I still have the problem, that I can't run my little java programs. When trying it, I get the message "The archive: /JavaBasics/lib/hamcrest-core-1.3.jar which is referenced by the classpath, does not exist."

At which point do I still reference the hamcrest archive? I don't get it... 

@mle-enso do you have an idea?

**Comment by mle-enso** [comment]
Try the following:
Open "Referenced Libraries" in the package explorer > right click on the hamcrest-core lib > select "Remove from build path".
Did you already Configure > Convert to Maven project?

**Comment by evainga** [comment]
did some stuff with the build path. I removed old paths and changed back and forth with the new one. Now all the red errors shown by eclipse before are gone, and it doesnt propose to add a build path any more. Still, I cant start the programm, now I get the Launch error "Editor des not contain a main type" after trying to start the Java Application (shortcut "J"). Is "J" still the right way to go, or should I press M for Maven? but when doing so, a dialogue opens asking me to insert a lot of things I don't know about...? (e.g. goals)

**Comment by mle-enso** [comment]
Usually you do not start Maven goals out of your IDE but rather from your command line. A common goal for running all tests there would be "mvn clean test". Poorly you do not have a good command line shell in your Windows operating system, but have a look in my fork's Travis build... call https://travis-ci.org/mle-enso/JavaBasics and search (CTRL-F) for "mvn clean test" – you will see three tests run (search for "BUILD SUCCESS"). That's the sole prove that everything is ok with your project. All other problems reside in your IDE respectively your project setup.
So forget about the M. Starting Java Applications (J) only works with classes which have a method with signature
`public static void main (String[] args)`
inside. These should be runnable via J, all other ones via right click on file => Run as TestNG test... shortcut N (T was already covered by JUnit).

**Comment by mle-enso** [comment]
I think, this is fixed.
